require('dotenv').config();
const express = require('express');
const path = require('path');
const helmet = require('helmet');
const cors = require('cors');
const app = express();
require('./config/db');
app.use(helmet());
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(express.static(path.join(__dirname, 'public')));
const heroRoutes = require('./routes/heroRoutes');
const constellationRoutes = require('./routes/constellationRoutes');
app.use('/api/heroes', heroRoutes);
app.use('/api/constellations', constellationRoutes);
app.set('view engine', 'ejs');
app.set('views', path.join(__dirname, 'views'));
app.get('/', (req, res) => { res.render('index'); });
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log('Server running on port ' + PORT));
